name: Debug
on:
  pull_request:
    types: [opened, synchronize, closed]
jobs:
  output-debug:
    runs-on: ubuntu-18.04
    steps:
      - uses: myathtutthu-genie/github-action-explore-debug@main
        with:
          jq_selector: ".pull_request"
  output-debug-two:
    runs-on: ubuntu-18.04
    steps:
      - uses: myathtutthu-genie/github-action-explore-debug@main
        with:
          jq_selector: ".pull_request"